sources : 
  - id: 1
    name: "Запись из личного архива №123321. Может быть автор."
    description: "Описание источника. Автор. Доступно по ссылке http://aboba"
  - id: 2
    name: "Запись из личного архива №123321-2. Может быть автор."
    description: "Описание источника. Автор. Доступно по ссылке http://aboba {source:1}[родительский источник]"