# обязательные параметры это id(должен быть уникальным), name, author
sources : 
  - id: 1
    name: "Запись из личного архива №123321. Может быть автор."
    description: "Описание источника. Автор. Доступно по ссылке http://aboba"
    date: 3
    author: "Абоба боба бибиович"
    link: "http://aboba"
  - id: 2
    name: "Запись из личного архива №123321-2. Может быть автор."
    description: "Описание источника. Автор. Доступно по ссылке http://aboba {source:1}[родительский источник]"
    author: "Абоба боба бибиович"
    date: 4
    link: "http://aboba"

source_fragments :
  - id: 1
    name: "ссылка на главу с жопой"
    source: 1
    description: "Глава пятая, строка двадцатая, улица Пушкина, дом Колотушкина"