# обязательные параметры это id(должен быть уникальным), name, author
sources : 
  - id: 1
    name: "Запись из личного архива №123321. Может быть автор."
    description: "Описание источника. Автор. Доступно по ссылке http://aboba"
    date: 3
    author: 1
    link: "http://aboba"
  - id: 2
    name: "Запись из личного архива №123321-2. Может быть автор."
    description: "Описание источника. Автор. Доступно по ссылке http://aboba {source:1}[родительский источник]"
    author: 2
    date: 4
    link: "http://aboba"
    type: "тип"
    subtype: "подтип"

source_fragments :
  - id: 1
    name: "ссылка на главу с жопой"
    source: 1
    description: "Глава пятая, строка двадцатая, улица Пушкина, дом Колотушкина"