# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.file_api_pb2 as file__api__pb2


class FileAPIStub(object):
    """сервис по управлению файлами:
    получать, отдавать, сохранять и пр. 
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/file_api.FileAPI/Ping',
                request_serializer=file__api__pb2.PingR.SerializeToString,
                response_deserializer=file__api__pb2.PongR.FromString,
                )
        self.AddFile = channel.unary_unary(
                '/file_api.FileAPI/AddFile',
                request_serializer=file__api__pb2.FileBinaryR.SerializeToString,
                response_deserializer=file__api__pb2.FileR.FromString,
                )
        self.GetFile = channel.unary_unary(
                '/file_api.FileAPI/GetFile',
                request_serializer=file__api__pb2.FileBaseR.SerializeToString,
                response_deserializer=file__api__pb2.FileBinaryR.FromString,
                )
        self.GetFileMetaInfo = channel.unary_unary(
                '/file_api.FileAPI/GetFileMetaInfo',
                request_serializer=file__api__pb2.FileBaseR.SerializeToString,
                response_deserializer=file__api__pb2.FileR.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/file_api.FileAPI/DeleteFile',
                request_serializer=file__api__pb2.FileBaseR.SerializeToString,
                response_deserializer=file__api__pb2.FileR.FromString,
                )
        self.PutFile = channel.unary_unary(
                '/file_api.FileAPI/PutFile',
                request_serializer=file__api__pb2.FileBinaryR.SerializeToString,
                response_deserializer=file__api__pb2.FileR.FromString,
                )
        self.GetManyFilesMetaInfo = channel.unary_unary(
                '/file_api.FileAPI/GetManyFilesMetaInfo',
                request_serializer=file__api__pb2.StorageSegmentR.SerializeToString,
                response_deserializer=file__api__pb2.FileSegmentR.FromString,
                )
        self.GetFilesMetaInfoCount = channel.unary_unary(
                '/file_api.FileAPI/GetFilesMetaInfoCount',
                request_serializer=file__api__pb2.StorageR.SerializeToString,
                response_deserializer=file__api__pb2.CountR.FromString,
                )


class FileAPIServicer(object):
    """сервис по управлению файлами:
    получать, отдавать, сохранять и пр. 
    """

    def Ping(self, request, context):
        """проверить работоспособность
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFile(self, request, context):
        """загрузить файл
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """получить файл
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileMetaInfo(self, request, context):
        """получить мета-информацию о файле (сгодится для проверки существования файла)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """удалить файл
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutFile(self, request, context):
        """сохранить/заменить файл
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManyFilesMetaInfo(self, request, context):
        """получить список мета-информацю всех (или отрезком) файлов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilesMetaInfoCount(self, request, context):
        """
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=file__api__pb2.PingR.FromString,
                    response_serializer=file__api__pb2.PongR.SerializeToString,
            ),
            'AddFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFile,
                    request_deserializer=file__api__pb2.FileBinaryR.FromString,
                    response_serializer=file__api__pb2.FileR.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=file__api__pb2.FileBaseR.FromString,
                    response_serializer=file__api__pb2.FileBinaryR.SerializeToString,
            ),
            'GetFileMetaInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileMetaInfo,
                    request_deserializer=file__api__pb2.FileBaseR.FromString,
                    response_serializer=file__api__pb2.FileR.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=file__api__pb2.FileBaseR.FromString,
                    response_serializer=file__api__pb2.FileR.SerializeToString,
            ),
            'PutFile': grpc.unary_unary_rpc_method_handler(
                    servicer.PutFile,
                    request_deserializer=file__api__pb2.FileBinaryR.FromString,
                    response_serializer=file__api__pb2.FileR.SerializeToString,
            ),
            'GetManyFilesMetaInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManyFilesMetaInfo,
                    request_deserializer=file__api__pb2.StorageSegmentR.FromString,
                    response_serializer=file__api__pb2.FileSegmentR.SerializeToString,
            ),
            'GetFilesMetaInfoCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilesMetaInfoCount,
                    request_deserializer=file__api__pb2.StorageR.FromString,
                    response_serializer=file__api__pb2.CountR.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file_api.FileAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileAPI(object):
    """сервис по управлению файлами:
    получать, отдавать, сохранять и пр. 
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_api.FileAPI/Ping',
            file__api__pb2.PingR.SerializeToString,
            file__api__pb2.PongR.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_api.FileAPI/AddFile',
            file__api__pb2.FileBinaryR.SerializeToString,
            file__api__pb2.FileR.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_api.FileAPI/GetFile',
            file__api__pb2.FileBaseR.SerializeToString,
            file__api__pb2.FileBinaryR.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFileMetaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_api.FileAPI/GetFileMetaInfo',
            file__api__pb2.FileBaseR.SerializeToString,
            file__api__pb2.FileR.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_api.FileAPI/DeleteFile',
            file__api__pb2.FileBaseR.SerializeToString,
            file__api__pb2.FileR.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_api.FileAPI/PutFile',
            file__api__pb2.FileBinaryR.SerializeToString,
            file__api__pb2.FileR.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetManyFilesMetaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_api.FileAPI/GetManyFilesMetaInfo',
            file__api__pb2.StorageSegmentR.SerializeToString,
            file__api__pb2.FileSegmentR.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFilesMetaInfoCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_api.FileAPI/GetFilesMetaInfoCount',
            file__api__pb2.StorageR.SerializeToString,
            file__api__pb2.CountR.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
