# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file-api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66ile-api.proto\x12\x08\x66ile_api\"\x07\n\x05PingR\"\x15\n\x05PongR\x12\x0c\n\x04pong\x18\x01 \x01(\t\"\x1b\n\x08StorageR\x12\x0f\n\x07storage\x18\x01 \x01(\t\"\x17\n\x06\x43ountR\x12\r\n\x05\x63ount\x18\x01 \x01(\r\"1\n\x0b\x46ileBinaryR\x12\"\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x14.file_api.FileBinary\"%\n\x05\x46ileR\x12\x1c\n\x04\x66ile\x18\x01 \x01(\x0b\x32\x0e.file_api.File\"-\n\tFileBaseR\x12 \n\x04\x66ile\x18\x01 \x01(\x0b\x32\x12.file_api.FileBase\">\n\x0fStorageSegmentR\x12\x0f\n\x07storage\x18\x01 \x01(\t\x12\r\n\x05start\x18\x02 \x01(\r\x12\x0b\n\x03\x65nd\x18\x03 \x01(\r\"-\n\x0c\x46ileSegmentR\x12\x1d\n\x05\x66iles\x18\x01 \x03(\x0b\x32\x0e.file_api.File\")\n\x08\x46ileBase\x12\x0f\n\x07storage\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"7\n\x04\x46ile\x12\x0f\n\x07storage\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\"K\n\nFileBinary\x12\x0f\n\x07storage\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0c\n\x04\x66ile\x18\x04 \x01(\x0c\x32\xd7\x03\n\x07\x46ileAPI\x12*\n\x04Ping\x12\x0f.file_api.PingR\x1a\x0f.file_api.PongR\"\x00\x12\x33\n\x07\x41\x64\x64\x46ile\x12\x15.file_api.FileBinaryR\x1a\x0f.file_api.FileR\"\x00\x12\x37\n\x07GetFile\x12\x13.file_api.FileBaseR\x1a\x15.file_api.FileBinaryR\"\x00\x12\x39\n\x0fGetFileMetaInfo\x12\x13.file_api.FileBaseR\x1a\x0f.file_api.FileR\"\x00\x12\x34\n\nDeleteFile\x12\x13.file_api.FileBaseR\x1a\x0f.file_api.FileR\"\x00\x12\x33\n\x07PutFile\x12\x15.file_api.FileBinaryR\x1a\x0f.file_api.FileR\"\x00\x12K\n\x14GetManyFilesMetaInfo\x12\x19.file_api.StorageSegmentR\x1a\x16.file_api.FileSegmentR\"\x00\x12?\n\x15GetFilesMetaInfoCount\x12\x12.file_api.StorageR\x1a\x10.file_api.CountR\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGR']._serialized_start=28
  _globals['_PINGR']._serialized_end=35
  _globals['_PONGR']._serialized_start=37
  _globals['_PONGR']._serialized_end=58
  _globals['_STORAGER']._serialized_start=60
  _globals['_STORAGER']._serialized_end=87
  _globals['_COUNTR']._serialized_start=89
  _globals['_COUNTR']._serialized_end=112
  _globals['_FILEBINARYR']._serialized_start=114
  _globals['_FILEBINARYR']._serialized_end=163
  _globals['_FILER']._serialized_start=165
  _globals['_FILER']._serialized_end=202
  _globals['_FILEBASER']._serialized_start=204
  _globals['_FILEBASER']._serialized_end=249
  _globals['_STORAGESEGMENTR']._serialized_start=251
  _globals['_STORAGESEGMENTR']._serialized_end=313
  _globals['_FILESEGMENTR']._serialized_start=315
  _globals['_FILESEGMENTR']._serialized_end=360
  _globals['_FILEBASE']._serialized_start=362
  _globals['_FILEBASE']._serialized_end=403
  _globals['_FILE']._serialized_start=405
  _globals['_FILE']._serialized_end=460
  _globals['_FILEBINARY']._serialized_start=462
  _globals['_FILEBINARY']._serialized_end=537
  _globals['_FILEAPI']._serialized_start=540
  _globals['_FILEAPI']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
