# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nosql-database-api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18nosql-database-api.proto\x12\x12nosql_database_api\"\r\n\x0bPingRequest\"\x1c\n\x0cPingResponse\x12\x0c\n\x04pong\x18\x01 \x01(\t\"0\n\x0ePutFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"1\n\x0fPutFileResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"%\n\x11\x44\x65leteFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"4\n\x12\x44\x65leteFileResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"0\n\x0e\x41\x64\x64\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"1\n\x0f\x41\x64\x64\x46ileResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"\"\n\x0eGetFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"1\n\x0fGetFileResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"7\n\x13GetManyFilesRequest\x12\x11\n\tstart_pos\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"$\n\x14GetManyFilesResponse\x12\x0c\n\x04TODO\x18\x01 \x01(\t2\xa5\x04\n\x10NoSQLDatabaseAPI\x12K\n\x04Ping\x12\x1f.nosql_database_api.PingRequest\x1a .nosql_database_api.PingResponse\"\x00\x12T\n\x07\x41\x64\x64\x46ile\x12\".nosql_database_api.AddFileRequest\x1a#.nosql_database_api.AddFileResponse\"\x00\x12T\n\x07PutFile\x12\".nosql_database_api.PutFileRequest\x1a#.nosql_database_api.PutFileResponse\"\x00\x12]\n\nDeleteFile\x12%.nosql_database_api.DeleteFileRequest\x1a&.nosql_database_api.DeleteFileResponse\"\x00\x12T\n\x07GetFile\x12\".nosql_database_api.GetFileRequest\x1a#.nosql_database_api.GetFileResponse\"\x00\x12\x63\n\x0cGetManyFiles\x12\'.nosql_database_api.GetManyFilesRequest\x1a(.nosql_database_api.GetManyFilesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nosql_database_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGREQUEST']._serialized_start=48
  _globals['_PINGREQUEST']._serialized_end=61
  _globals['_PINGRESPONSE']._serialized_start=63
  _globals['_PINGRESPONSE']._serialized_end=91
  _globals['_PUTFILEREQUEST']._serialized_start=93
  _globals['_PUTFILEREQUEST']._serialized_end=141
  _globals['_PUTFILERESPONSE']._serialized_start=143
  _globals['_PUTFILERESPONSE']._serialized_end=192
  _globals['_DELETEFILEREQUEST']._serialized_start=194
  _globals['_DELETEFILEREQUEST']._serialized_end=231
  _globals['_DELETEFILERESPONSE']._serialized_start=233
  _globals['_DELETEFILERESPONSE']._serialized_end=285
  _globals['_ADDFILEREQUEST']._serialized_start=287
  _globals['_ADDFILEREQUEST']._serialized_end=335
  _globals['_ADDFILERESPONSE']._serialized_start=337
  _globals['_ADDFILERESPONSE']._serialized_end=386
  _globals['_GETFILEREQUEST']._serialized_start=388
  _globals['_GETFILEREQUEST']._serialized_end=422
  _globals['_GETFILERESPONSE']._serialized_start=424
  _globals['_GETFILERESPONSE']._serialized_end=473
  _globals['_GETMANYFILESREQUEST']._serialized_start=475
  _globals['_GETMANYFILESREQUEST']._serialized_end=530
  _globals['_GETMANYFILESRESPONSE']._serialized_start=532
  _globals['_GETMANYFILESRESPONSE']._serialized_end=568
  _globals['_NOSQLDATABASEAPI']._serialized_start=571
  _globals['_NOSQLDATABASEAPI']._serialized_end=1120
# @@protoc_insertion_point(module_scope)
