# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.nosql_database_api_pb2 as nosql__database__api__pb2


class NoSQLDatabaseAPIStub(object):
    """сервис работы NoSQL базы данных, используемой различными сервисами, например,
    для запоминания сохранённых файлов на FTP-сервере
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/nosql_database_api.NoSQLDatabaseAPI/Ping',
                request_serializer=nosql__database__api__pb2.PingRequest.SerializeToString,
                response_deserializer=nosql__database__api__pb2.PingResponse.FromString,
                )
        self.AddFile = channel.unary_unary(
                '/nosql_database_api.NoSQLDatabaseAPI/AddFile',
                request_serializer=nosql__database__api__pb2.AddFileRequest.SerializeToString,
                response_deserializer=nosql__database__api__pb2.AddFileResponse.FromString,
                )
        self.PutFile = channel.unary_unary(
                '/nosql_database_api.NoSQLDatabaseAPI/PutFile',
                request_serializer=nosql__database__api__pb2.PutFileRequest.SerializeToString,
                response_deserializer=nosql__database__api__pb2.PutFileResponse.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/nosql_database_api.NoSQLDatabaseAPI/DeleteFile',
                request_serializer=nosql__database__api__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=nosql__database__api__pb2.DeleteFileResponse.FromString,
                )
        self.GetFile = channel.unary_unary(
                '/nosql_database_api.NoSQLDatabaseAPI/GetFile',
                request_serializer=nosql__database__api__pb2.GetFileRequest.SerializeToString,
                response_deserializer=nosql__database__api__pb2.GetFileResponse.FromString,
                )
        self.GetManyFiles = channel.unary_unary(
                '/nosql_database_api.NoSQLDatabaseAPI/GetManyFiles',
                request_serializer=nosql__database__api__pb2.GetManyFilesRequest.SerializeToString,
                response_deserializer=nosql__database__api__pb2.GetManyFilesResponse.FromString,
                )


class NoSQLDatabaseAPIServicer(object):
    """сервис работы NoSQL базы данных, используемой различными сервисами, например,
    для запоминания сохранённых файлов на FTP-сервере
    """

    def Ping(self, request, context):
        """проверить работоспособность
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddFile(self, request, context):
        """сохранить файл в базе
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PutFile(self, request, context):
        """сохранить/заменить (запомнить) файл в базе
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """удалить (забыть) файл в базе
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """получить файл из базы
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetManyFiles(self, request, context):
        """получить несколько файлов из базы
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NoSQLDatabaseAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=nosql__database__api__pb2.PingRequest.FromString,
                    response_serializer=nosql__database__api__pb2.PingResponse.SerializeToString,
            ),
            'AddFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFile,
                    request_deserializer=nosql__database__api__pb2.AddFileRequest.FromString,
                    response_serializer=nosql__database__api__pb2.AddFileResponse.SerializeToString,
            ),
            'PutFile': grpc.unary_unary_rpc_method_handler(
                    servicer.PutFile,
                    request_deserializer=nosql__database__api__pb2.PutFileRequest.FromString,
                    response_serializer=nosql__database__api__pb2.PutFileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=nosql__database__api__pb2.DeleteFileRequest.FromString,
                    response_serializer=nosql__database__api__pb2.DeleteFileResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=nosql__database__api__pb2.GetFileRequest.FromString,
                    response_serializer=nosql__database__api__pb2.GetFileResponse.SerializeToString,
            ),
            'GetManyFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManyFiles,
                    request_deserializer=nosql__database__api__pb2.GetManyFilesRequest.FromString,
                    response_serializer=nosql__database__api__pb2.GetManyFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nosql_database_api.NoSQLDatabaseAPI', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NoSQLDatabaseAPI(object):
    """сервис работы NoSQL базы данных, используемой различными сервисами, например,
    для запоминания сохранённых файлов на FTP-сервере
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nosql_database_api.NoSQLDatabaseAPI/Ping',
            nosql__database__api__pb2.PingRequest.SerializeToString,
            nosql__database__api__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nosql_database_api.NoSQLDatabaseAPI/AddFile',
            nosql__database__api__pb2.AddFileRequest.SerializeToString,
            nosql__database__api__pb2.AddFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PutFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nosql_database_api.NoSQLDatabaseAPI/PutFile',
            nosql__database__api__pb2.PutFileRequest.SerializeToString,
            nosql__database__api__pb2.PutFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nosql_database_api.NoSQLDatabaseAPI/DeleteFile',
            nosql__database__api__pb2.DeleteFileRequest.SerializeToString,
            nosql__database__api__pb2.DeleteFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nosql_database_api.NoSQLDatabaseAPI/GetFile',
            nosql__database__api__pb2.GetFileRequest.SerializeToString,
            nosql__database__api__pb2.GetFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetManyFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nosql_database_api.NoSQLDatabaseAPI/GetManyFiles',
            nosql__database__api__pb2.GetManyFilesRequest.SerializeToString,
            nosql__database__api__pb2.GetManyFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
